## 類似度の定義

In [40]:
# !pip install numpy

In [41]:
import numpy as np
from numpy import dtype,ndarray
from typing import Any, Callable
import math

pic_1: ndarray[tuple[int, ...], dtype[Any]] =np.array(
    [[1, 2],
    [3, 4]]
)

pic_2: ndarray[tuple[int, ...], dtype[Any]] =np.array(
    [[2, 2],
    [2, 2]]
)

### 相違度: Sum of Square Distance

$$
R_{SSD} = \sum_{i,j}(I(i,j) - T(i,j))^2
$$

### 相違度: Sum of Absolute Distance
$$
R_{SAD} = \sum_{i,j}|{I(i,j) - T(i,j)}|
$$

### 類似度: Normalized Cross Correlation
$$
R_{NCC} = \frac{\sum_{i,j}I(i,j)T(i,j)}{\sqrt{\sum_{i,j}I(i,j)^2 \sum_{i,j}T(i,j)^2}}
$$


In [42]:
# Practice1


def SSD(image:ndarray, template:ndarray) -> float:
    return np.sum((image - template) ** 2)

def SAD(image:ndarray, template:ndarray) -> float:
    return np.sum(abs(image - template))

def NCC(image:ndarray, template:ndarray) -> float:
    if np.sqrt(np.sum(image ** 2) * np.sum(template ** 2)) != 0:
        return (np.sum(image * template)) / np.sqrt(np.sum(image ** 2) * np.sum(template ** 2))
    return 0.0


In [43]:
print(f'SAD:{SAD(pic_1,pic_2)}\n\
      SSD:{SSD(pic_1,pic_2)}\n\
      NCC:{NCC(pic_1,pic_2)}\n')

SAD:4
      SSD:6
      NCC:0.9128709291752769



In [44]:
# Practice2

from numpy import dtype, float64


image: ndarray[tuple[int, ...], dtype[Any]] = np.array(
    [[1, 1, 2, 3, 4],
     [1, 1, 2, 3, 4],
     [5, 5, 6, 7, 8],
     [5, 5, 6, 7, 8],
     [9, 9, 10, 11, 12]
     ]
)

template: ndarray[tuple[int, ...], dtype[Any]] = np.array(
    [[1,2],
     [5,6]]
)

def template_matching(image:ndarray, 
                      template:ndarray, 
                      similarity_metric:Callable[[ndarray,ndarray],float]):
    image_height, image_width = image.shape
    template_height, template_width = template.shape
    
    result_height = image_height - template_height + 1
    result_width = image_width - template_width + 1

    return np.array([
        [similarity_metric(image[y:y+template_height, x:x+template_width], template)
         for x in range(result_width)]
         for y in range(result_height)
    ])


print(template_matching(image,template,SAD))


[[10  8  8  8]
 [ 2  0  4  8]
 [ 8  8 12 16]
 [14 16 20 24]]


In [45]:
image2: ndarray[tuple[int, ...], dtype[Any]] = np.array(
    [[1, 1, 2, 3, 4],
     [1, 1, 2, 3, 4],
     [6, 5, 1, 7, 8],
     [5, 6, 0, 7, 8],
     [9, 9, 10, 11, 12]
     ]
)
# 横sobelフィルタ
horizontal_sobel_filter = np.array(
    [[-1,0,1],
     [-2,0,2],
     [-1,0,1]]
)

# 縦sobelフィルタ
parallels_sobel_filter = np.array(
    [[-1,-2,-1],
     [0,0,0],
     [1,2,3]]
)


In [46]:
def sobel_filter(target_x, target_y, image, filter):
    return np.sum(image[target_y-1 : target_y+2, target_x-1 : target_x+2] * filter)

# ヘルパー関数
def power_sum(x, y):
    return x**2 + y**2

In [ ]:
I_x = sobel_filter(1,2,image2,horizontal_sobel_filter)
I_y = sobel_filter(1,2,image2,parallels_sobel_filter)
power_sum_I = power_sum(I_x, I_y)
atan2_I = math.atan2(I_y,I_x) * 180 / math.pi

In [48]:
print(power_sum_I)

340
