## 類似度の定義

In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 255.0 kB/s eta 0:00:0000:0100:02


In [21]:
import numpy as np
from numpy import dtype,ndarray
from typing import Any, Callable

pic_1: ndarray[tuple[int, ...], dtype[Any]] =np.array(
    [[3, 3],
    [3, 3]]
)

pic_2: ndarray[tuple[int, ...], dtype[Any]] =np.array(
    [[5, 2],
    [2, 4]]
)

### 相違度: Sum of Square Distance

$$
R_{SSD} = \sum_{i,j}(I(i,j) - T(i,j))^2
$$

### 相違度: Sum of Absolute Distance
$$
R_{SAD} = \sum_{i,j}|{I(i,j) - T(i,j)}|
$$

### 類似度: Normalized Cross Correlation
$$
R_{NCC} = \frac{\sum_{i,j}I(i,j)T(i,j)}{\sqrt{\sum_{i,j}I(i,j)^2 \sum_{i,j}T(i,j)^2}}
$$


In [17]:
# Practice1


def SSD(image:ndarray, template:ndarray) -> float:
    return np.sum((image - template) ** 2)

def SAD(image:ndarray, template:ndarray) -> float:
    return np.sum(abs(image - template))

def NCC(image:ndarray, template:ndarray) -> float:
    if np.sqrt(np.sum(image ** 2) * np.sum(template ** 2)) != 0:
        return (np.sum(image * template)) / np.sqrt(np.sum(image ** 2) * np.sum(template ** 2))
    return 0.0


In [ ]:
print(f'SAD:{SAD(pic_1,pic_2)}\n\
      SSD:{SSD(pic_1,pic_2)}\n\
      NCC:{NCC(pic_1,pic_2)}\n')

SAD:5
      SSD:7
      NCC:0.9285714285714286



In [ ]:
# Practice2

from numpy import dtype, float64


image: ndarray[tuple[int, ...], dtype[Any]] = np.array(
    [[1, 1, 2, 3, 4],
     [1, 1, 2, 3, 4],
     [5, 5, 6, 7, 8],
     [5, 5, 6, 7, 8],
     [9, 9, 10, 11, 12]
     ]
)

template: ndarray[tuple[int, ...], dtype[Any]] = np.array(
    [[1,2],
     [5,6]]
)

def template_matching(image:ndarray, 
                      template:ndarray, 
                      similarity_metric:Callable[[ndarray,ndarray],float]):
    image_height, image_width = image.shape
    template_height, template_width = template.shape
    
    result_height = image_height - template_height + 1
    result_width = image_width - template_width + 1

    return np.array([
        [similarity_metric(image[y:y+template_height, x:x+template_width], template)
         for x in range(result_width)]
         for y in range(result_height)
    ])


print(template_matching(image,template,SAD))


[[10  8  8  8]
 [ 2  0  4  8]
 [ 8  8 12 16]
 [14 16 20 24]]
